# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profanedb/protobuf/storage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='profanedb/protobuf/storage.proto',
  package='profanedb.protobuf',
  syntax='proto3',
  serialized_pb=_b('\n profanedb/protobuf/storage.proto\x12\x12profanedb.protobuf\"9\n\x03Key\x12\x14\n\x0cmessage_type\x18\x01 \x01(\t\x12\r\n\x05\x66ield\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x0c\"H\n\x0fStorableMessage\x12$\n\x03key\x18\x01 \x01(\x0b\x32\x17.profanedb.protobuf.Key\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\"~\n\x0fMessageTreeNode\x12\x34\n\x07message\x18\x01 \x01(\x0b\x32#.profanedb.protobuf.StorableMessage\x12\x35\n\x08\x63hildren\x18\x02 \x03(\x0b\x32#.profanedb.protobuf.MessageTreeNodeBU\n\x16\x63om.profanedb.protobufZ gitlab.com/profanedb/protobuf/db\xa2\x02\x03PDB\xaa\x02\x12ProfaneDB.Protobufb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='profanedb.protobuf.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='profanedb.protobuf.Key.message_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field', full_name='profanedb.protobuf.Key.field', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='profanedb.protobuf.Key.value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=113,
)


_STORABLEMESSAGE = _descriptor.Descriptor(
  name='StorableMessage',
  full_name='profanedb.protobuf.StorableMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='profanedb.protobuf.StorableMessage.key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='payload', full_name='profanedb.protobuf.StorableMessage.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=187,
)


_MESSAGETREENODE = _descriptor.Descriptor(
  name='MessageTreeNode',
  full_name='profanedb.protobuf.MessageTreeNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='profanedb.protobuf.MessageTreeNode.message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='children', full_name='profanedb.protobuf.MessageTreeNode.children', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=315,
)

_STORABLEMESSAGE.fields_by_name['key'].message_type = _KEY
_MESSAGETREENODE.fields_by_name['message'].message_type = _STORABLEMESSAGE
_MESSAGETREENODE.fields_by_name['children'].message_type = _MESSAGETREENODE
DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['StorableMessage'] = _STORABLEMESSAGE
DESCRIPTOR.message_types_by_name['MessageTreeNode'] = _MESSAGETREENODE

Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), dict(
  DESCRIPTOR = _KEY,
  __module__ = 'profanedb.protobuf.storage_pb2'
  # @@protoc_insertion_point(class_scope:profanedb.protobuf.Key)
  ))
_sym_db.RegisterMessage(Key)

StorableMessage = _reflection.GeneratedProtocolMessageType('StorableMessage', (_message.Message,), dict(
  DESCRIPTOR = _STORABLEMESSAGE,
  __module__ = 'profanedb.protobuf.storage_pb2'
  # @@protoc_insertion_point(class_scope:profanedb.protobuf.StorableMessage)
  ))
_sym_db.RegisterMessage(StorableMessage)

MessageTreeNode = _reflection.GeneratedProtocolMessageType('MessageTreeNode', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGETREENODE,
  __module__ = 'profanedb.protobuf.storage_pb2'
  # @@protoc_insertion_point(class_scope:profanedb.protobuf.MessageTreeNode)
  ))
_sym_db.RegisterMessage(MessageTreeNode)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\026com.profanedb.protobufZ gitlab.com/profanedb/protobuf/db\242\002\003PDB\252\002\022ProfaneDB.Protobuf'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
