# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import profanedb.protobuf.db_pb2 as profanedb_dot_protobuf_dot_db__pb2


class DbStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/profanedb.protobuf.Db/Get',
        request_serializer=profanedb_dot_protobuf_dot_db__pb2.GetReq.SerializeToString,
        response_deserializer=profanedb_dot_protobuf_dot_db__pb2.GetResp.FromString,
        )
    self.Put = channel.unary_unary(
        '/profanedb.protobuf.Db/Put',
        request_serializer=profanedb_dot_protobuf_dot_db__pb2.PutReq.SerializeToString,
        response_deserializer=profanedb_dot_protobuf_dot_db__pb2.PutResp.FromString,
        )
    self.Delete = channel.unary_unary(
        '/profanedb.protobuf.Db/Delete',
        request_serializer=profanedb_dot_protobuf_dot_db__pb2.DelReq.SerializeToString,
        response_deserializer=profanedb_dot_protobuf_dot_db__pb2.DelResp.FromString,
        )


class DbServicer(object):

  def Get(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Put(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DbServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=profanedb_dot_protobuf_dot_db__pb2.GetReq.FromString,
          response_serializer=profanedb_dot_protobuf_dot_db__pb2.GetResp.SerializeToString,
      ),
      'Put': grpc.unary_unary_rpc_method_handler(
          servicer.Put,
          request_deserializer=profanedb_dot_protobuf_dot_db__pb2.PutReq.FromString,
          response_serializer=profanedb_dot_protobuf_dot_db__pb2.PutResp.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=profanedb_dot_protobuf_dot_db__pb2.DelReq.FromString,
          response_serializer=profanedb_dot_protobuf_dot_db__pb2.DelResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'profanedb.protobuf.Db', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
