// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: profanedb/protobuf/options.proto
// Original file comments:
//
// ProfaneDB - A Protocol Buffers database.
// Copyright (C) 2017  "Giorgio Azzinnaro" <giorgio.azzinnaro@gmail.com>
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//
#ifndef GRPC_profanedb_2fprotobuf_2foptions_2eproto__INCLUDED
#define GRPC_profanedb_2fprotobuf_2foptions_2eproto__INCLUDED

#include "profanedb/protobuf/options.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace profanedb {
namespace protobuf {

}  // namespace protobuf
}  // namespace profanedb


#endif  // GRPC_profanedb_2fprotobuf_2foptions_2eproto__INCLUDED
