// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: profanedb/protobuf/storage.proto

#include "profanedb/protobuf/storage.pb.h"
#include "profanedb/protobuf/storage.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace profanedb {
namespace protobuf {

}  // namespace profanedb
}  // namespace protobuf

